/// @file zmq_server.h
/// @brief ZMQ REP/PUB server that drives a confd Runtime — the
/// standalone, multi-process half of the embeddable library.
///
/// Binds a REP control socket and a PUB event socket, runs a background
/// accept loop, and hands every decoded Request to
/// Runtime::HandleRequest — the exact same core the in-process
/// transport calls. Client CLI + daemon and single-binary embedded are
/// therefore one code path; only the transport differs.
// Copyright (c) 2026 Einheit Networks

#ifndef INCLUDE_EINHEIT_CLI_CONFD_ZMQ_SERVER_H_
#define INCLUDE_EINHEIT_CLI_CONFD_ZMQ_SERVER_H_

#include <memory>
#include <string>

#include "einheit/cli/confd/runtime.h"
#include "einheit/cli/protocol/envelope.h"

namespace einheit::cli::confd {

/// Endpoints for a ZmqServer. Empty endpoints get an autogenerated
/// tmpdir ipc:// path (handy for tests).
struct ZmqServerConfig {
  /// ipc:// / tcp:// control (REP) endpoint. Empty → tmpdir ipc://.
  std::string control_endpoint;
  /// ipc:// / tcp:// event (PUB) endpoint. Empty → tmpdir ipc://.
  std::string event_endpoint;
};

/// Background ZMQ server bound to a Runtime. Destructor stops the loop
/// and joins. The Runtime must outlive the server.
class ZmqServer {
 public:
  /// Bind sockets and start the accept loop.
  /// @param runtime Config runtime to drive (borrowed).
  /// @param cfg Endpoint configuration.
  ZmqServer(Runtime &runtime, ZmqServerConfig cfg = {});
  ~ZmqServer();

  ZmqServer(const ZmqServer &) = delete;
  auto operator=(const ZmqServer &) -> ZmqServer & = delete;

  /// Bound control endpoint — hand to a client transport.
  auto ControlEndpoint() const -> const std::string &;
  /// Bound event endpoint.
  auto EventEndpoint() const -> const std::string &;

  /// Publish an event to subscribers on the PUB channel.
  /// @param ev Event to publish.
  auto Publish(const protocol::Event &ev) -> void;

  // Opaque implementation.
  struct Impl;

 private:
  std::unique_ptr<Impl> impl_;
};

}  // namespace einheit::cli::confd

#endif  // INCLUDE_EINHEIT_CLI_CONFD_ZMQ_SERVER_H_
