/// @file docs.cc
/// @brief Operator reference generation.
// Copyright (c) 2026 Einheit Networks

#include "einheit/cli/docs.h"

#include <algorithm>
#include <format>
#include <string>
#include <vector>

#include "einheit/cli/render/table.h"

namespace einheit::cli::docs {
namespace {

/// Markdown table cells may not contain bare pipes or newlines.
auto Escape(const std::string &s) -> std::string {
  std::string out;
  out.reserve(s.size());
  for (const char c : s) {
    if (c == '|') {
      out += "\\|";
    } else if (c == '\n') {
      out += ' ';
    } else {
      out += c;
    }
  }
  return out;
}

auto RoleLabel(RoleGate role) -> const char * {
  switch (role) {
    case RoleGate::AdminOnly:       return "admin";
    case RoleGate::OperatorOrAdmin: return "operator";
    case RoleGate::AnyAuthenticated:
    default:                        return "any";
  }
}

/// `command <required> [optional]` synopsis from the spec.
auto Synopsis(const CommandSpec &spec) -> std::string {
  std::string out = spec.path;
  for (const auto &arg : spec.args) {
    out += arg.required ? std::format(" <{}>", arg.name)
                        : std::format(" [{}]", arg.name);
  }
  return out;
}

/// Whether a verb belongs to the candidate-config lifecycle.
auto IsLifecycle(const CommandSpec &spec) -> bool {
  static const std::vector<std::string> kPrefixes = {
      "configure", "set", "delete", "commit", "confirm", "rollback",
      "save", "load", "show config", "show configs", "show commits",
      "show commit", "show diff", "show schema",
  };
  for (const auto &p : kPrefixes) {
    if (spec.path == p || spec.path.rfind(p + " ", 0) == 0) {
      return true;
    }
  }
  return false;
}

auto EmitCommandTable(std::string &md,
                      const std::vector<const CommandSpec *> &specs)
    -> void {
  md += "| Command | Role | Description |\n";
  md += "|---|---|---|\n";
  for (const auto *spec : specs) {
    md += std::format("| `{}` | {} | {} |\n", Synopsis(*spec),
                      RoleLabel(spec->role), Escape(spec->help));
  }
  md += "\n";
}

}  // namespace

auto GenerateReference(const ProductMetadata &meta,
                       const CommandTree &tree,
                       const schema::Schema &schema) -> std::string {
  std::string md;
  md += std::format("# {} — CLI Reference\n\n", meta.display_name);
  md += std::format(
      "Generated by `--dump-docs` from the running binary "
      "(product `{}`, version {}). **Do not edit** — wording fixes "
      "belong in the schema help strings and command specs; "
      "regenerate and commit.\n\n",
      meta.id, meta.version);

  md += "## Configuration paths\n\n";
  md += "Set inside a `configure` session: `set <path> <value>`, "
        "`delete <path>`, then `commit`. `<name>` marks a key you "
        "choose (a port, an interface, a VLAN id).\n\n";
  md += "| Path | Type | Default | Description |\n";
  md += "|---|---|---|---|\n";
  const auto table = schema::BuildSchema(schema);
  for (const auto &row : table.rows) {
    const auto cell = [&row](std::size_t i) -> std::string {
      return i < row.size() ? Escape(row[i].text) : std::string();
    };
    md += std::format("| `{}` | {} | {} | {} |\n", cell(0), cell(1),
                      cell(2).empty() ? "—" : cell(2), cell(3));
  }
  md += "\n";

  std::vector<const CommandSpec *> lifecycle;
  std::vector<const CommandSpec *> shows;
  std::vector<const CommandSpec *> operational;
  for (const auto &[path, spec] : tree.by_path) {
    if (IsLifecycle(spec)) {
      lifecycle.push_back(&spec);
    } else if (path.rfind("show ", 0) == 0) {
      shows.push_back(&spec);
    } else {
      operational.push_back(&spec);
    }
  }
  const auto by_path = [](const CommandSpec *a,
                          const CommandSpec *b) {
    return a->path < b->path;
  };
  std::sort(lifecycle.begin(), lifecycle.end(), by_path);
  std::sort(shows.begin(), shows.end(), by_path);
  std::sort(operational.begin(), operational.end(), by_path);

  md += "## Configuration lifecycle commands\n\n";
  EmitCommandTable(md, lifecycle);
  md += "## Show commands\n\n";
  EmitCommandTable(md, shows);
  md += "## Operational commands\n\n";
  EmitCommandTable(md, operational);
  return md;
}

}  // namespace einheit::cli::docs
